### ISSUE TITLE
Can't migrate to version 0.5.0

### ISSUE THREAD

**Issue by vegansk** [gcanti/io-ts#54]
The code below produces very interesting effects.
- The compiler of version 2.4.0 just hangs
- The compiler of version 2.4.1 crashes with OOM 
- The compiler of version 2.3.4 produces error.
Code:
```ts
export const AccountTypeEtType = t.union([
  t.literal("ISSUE"),
  t.literal("EMITENT"),
  t.literal("OWNER"),
  t.literal("NOMINEE"),
  t.literal("TRUSTEE"),
  t.literal("PLEDGEE"),
  t.literal("UNKNOWN"),
  t.literal("NOTARY"),
  t.literal("RIGHTS"),
  t.literal("TREASURY"),
  t.literal("DEPOSIT"),
  t.literal("NDCD"),
  t.literal("FORNOMINEE"),
  t.literal("FORAUTHOR"),
  t.literal("DEPOPROG")
], "AccountTypeEt")
export type AccountTypeEt = t.TypeOf<typeof AccountTypeEtType>
```
Error:
```
src/core/types/polaris.ts(8,42): error TS2345: Argument of type '[LiteralType<"ISSUE">, LiteralType<"EMITENT">, LiteralType<"OWNER">, LiteralType<"NOMINEE">, Lite...' is not assignable to parameter of type '[LiteralType<"ISSUE">, LiteralType<"EMITENT">]'.
  Types of property 'pop' are incompatible.
    Type '() => LiteralType<"ISSUE"> | LiteralType<"EMITENT"> | LiteralType<"OWNER"> | LiteralType<"NOMINEE...' is not assignable to type '() => LiteralType<"ISSUE"> | LiteralType<"EMITENT"> | undefined'.
      Type 'LiteralType<"ISSUE"> | LiteralType<"EMITENT"> | LiteralType<"OWNER"> | LiteralType<"NOMINEE"> | L...' is not assignable to type 'LiteralType<"ISSUE"> | LiteralType<"EMITENT"> | undefined'.
        Type 'LiteralType<"OWNER">' is not assignable to type 'LiteralType<"ISSUE"> | LiteralType<"EMITENT"> | undefined'.
          Type 'LiteralType<"OWNER">' is not assignable to type 'LiteralType<"EMITENT">'.
            Type '"OWNER"' is not assignable to type '"EMITENT"'.
```

The problem disappears when I leave only 5 enum values. I know that the `union` function is specialized for up to 5 type parameters maximum. But it worked with the io-ts version 0.4.0.

**Comment by gcanti** [comment]
> I know that the union function is specialized for up to 5 type parameters maximum. But it worked with the io-ts version 0.4.0

Yep, I removed many overloadings because they make VSCode Code Helper very slow. Please try with `t.keyof` which is meant to handle large string unions

ts 2.4.1 is not supported because of the fp-ts dependency (see https://github.com/gcanti/fp-ts/issues/138 for details)

**Comment by vegansk** [comment]
I can't use `t.keyof` in the code below, and it has the same problem:
```ts
function mkFormStateType<S extends string, T>(formName: S, dataType: t.Type<T>, typeName: string) {
  return mkType({ type: t.literal<S>(formName) }, { data: dataType }, typeName)
}

export const DocumentStateType = mkFormStateType("document", DocumentFormType, "DocumentState")
export type DocumentState = t.TypeOf<typeof DocumentStateType>

export const TestFormStateType = mkFormStateType("testForm", TestFormType, "TestFormState")
export type TestFormState = t.TypeOf<typeof TestFormStateType>

export const RegistrarFormStateType = mkFormStateType("registrarForm", RegistrarFormType, "RegistrarFormState")
export type RegistrarFormState = t.TypeOf<typeof RegistrarFormStateType>

export const ServicePriceFormStateType = mkFormStateType("servicePriceForm", ServicePriceFormType, "ServicePriceFormState")
export type ServicePriceFormState = t.TypeOf<typeof ServicePriceFormStateType>

export const IssuerFormStateType = mkFormStateType("issuerForm", IssuerFormType, "IssuerFormStateType")
export type IssuerFormState = t.TypeOf<typeof IssuerFormStateType>

export const PriceListFormStateType = mkFormStateType("priceListForm", PriceListFormType, "PriceListFormState")
export type PriceListFormState = t.TypeOf<typeof PriceListFormStateType>

export const ReceivingCenterFormStateType = mkFormStateType("receivingCenterForm", ReceivingCenterFormType, "ReceivingCenterFormState")
export type ReceivingCenterFormState = t.TypeOf<typeof ReceivingCenterFormStateType>

export const FormStateType = t.union([
  RegistrarFormStateType,
  DocumentStateType,
  TestFormStateType,
  ReceivingCenterFormStateType,
  IssuerFormStateType,
  ServicePriceFormStateType,
  PriceListFormStateType
])
```

**Comment by vegansk** [comment]
And I can't find extra overloadings in 0.4.0: https://github.com/gcanti/io-ts/blob/0.4.x/src/index.ts#L413-L444

**Comment by gcanti** [comment]
Ah.. you are right, I removed the overloadings while transitioning from 0.2.x to 0.3.x, sorry for the confusion

**Comment by gcanti** [comment]
@vegansk with ts 2.3.4  I can't repro, the following type definition works fine for me

```ts
export const AccountTypeEtType = t.union([
  t.literal("ISSUE"),
  t.literal("EMITENT"),
  t.literal("OWNER"),
  t.literal("NOMINEE"),
  t.literal("TRUSTEE"),
  t.literal("PLEDGEE"),
  t.literal("UNKNOWN"),
  t.literal("NOTARY"),
  t.literal("RIGHTS"),
  t.literal("TREASURY"),
  t.literal("DEPOSIT"),
  t.literal("NDCD"),
  t.literal("FORNOMINEE"),
  t.literal("FORAUTHOR"),
  t.literal("DEPOPROG")
], "AccountTypeEt")
export type AccountTypeEt = t.TypeOf<typeof AccountTypeEtType>
```

The behavior of TypeScript with more than 5 union members is weird though. From this definition

```ts
export const AccountTypeEtType = t.union(
  // 5 union members
  [t.literal('ISSUE'), t.literal('EMITENT'), t.literal('OWNER'), t.literal('NOMINEE'), t.literal('TRUSTEE')],
  'AccountTypeEt'
)
export type AccountTypeEt = t.TypeOf<typeof AccountTypeEtType>
```

TypeScript correctly infers 

```ts
function union<t.LiteralType<"ISSUE">, t.LiteralType<"EMITENT">, t.LiteralType<"OWNER">, t.LiteralType<"NOMINEE">, t.LiteralType<"TRUSTEE">>(types: [t.LiteralType<"ISSUE">, t.LiteralType<"EMITENT">, t.LiteralType<"OWNER">, t.LiteralType<"NOMINEE">, t.LiteralType<"TRUSTEE">], name?: string | undefined): t.UnionType<[t.LiteralType<"ISSUE">, t.LiteralType<"EMITENT">, t.LiteralType<"OWNER">, t.LiteralType<"NOMINEE">, t.LiteralType<"TRUSTEE">], "ISSUE" | "EMITENT" | "OWNER" | "NOMINEE" | "TRUSTEE">
```

But if I add another member

```ts
export const AccountTypeEtType = t.union(
  [
    t.literal('ISSUE'),
    t.literal('EMITENT'),
    t.literal('OWNER'),
    t.literal('NOMINEE'),
    t.literal('TRUSTEE'),
    t.literal('PLEDGEE')
  ],
  'AccountTypeEt'
)
export type AccountTypeEt = t.TypeOf<typeof AccountTypeEtType>
```

then TypeScript infers the following weird type

```ts
function union<t.LiteralType<"ISSUE"> | t.LiteralType<"EMITENT"> | t.LiteralType<"OWNER"> | t.LiteralType<"NOMINEE"> | t.LiteralType<"TRUSTEE"> | t.LiteralType<"PLEDGEE">>(types: [t.LiteralType<"ISSUE"> | t.LiteralType<"EMITENT"> | t.LiteralType<"OWNER"> | t.LiteralType<"NOMINEE"> | t.LiteralType<"TRUSTEE"> | t.LiteralType<"PLEDGEE">], name?: string | undefined): t.UnionType<[t.LiteralType<"ISSUE"> | t.LiteralType<"EMITENT"> | t.LiteralType<"OWNER"> | t.LiteralType<"NOMINEE"> | t.LiteralType<"TRUSTEE"> | t.LiteralType<"PLEDGEE">], "ISSUE" | "EMITENT" | "OWNER" | "NOMINEE" | "TRUSTEE" | "PLEDGEE">
```

It seems that TypeScript picks the first overloading

```ts
export declare function union<A extends Any>(types: [A], name?: string): UnionType<[A], TypeOf<A>>;
```

and somehow manages to create a union.

Here's a small repro of the weird behavior

```ts
declare function f<A>(x: [A]): void
f([1]) // function f<number>(x: [number]): void
f([1, 'a']) // function f<string | number>(x: [string | number]): void
```

**Comment by vegansk** [comment]
I also can't reproduce the issue in the small project, only in the original one, but it's closed source :-(

**Comment by gcanti** [comment]
As a workaround you could try with unions of unions, the resulting type should be the same.

So for unions of string literals you could just use `t.keyof`, for unions of interfaces you could group them

```ts
const T1 = t.interface({
  a1: t.string
})
const T2 = t.interface({
  a2: t.string
})
const T3 = t.interface({
  a3: t.string
})
const T4 = t.interface({
  a4: t.string
})
const T5 = t.interface({
  a5: t.string
})
const T6 = t.interface({
  a6: t.string
})
const T7 = t.interface({
  a7: t.string
})

const U = t.union([t.union([T1, T2, T3, T4, T5]), t.union([T6, T7])])

type UT = t.TypeOf<typeof U>
```

**Comment by vegansk** [comment]
Thanks. Will try to reproduce it in minimal example to send bug to the compiler's issue tracker.

**Comment by gcanti** [comment]
> It seems that TypeScript picks the first overloading and somehow manages to create a union.

@vegansk based on this observation I've had an idea, if I change the signature of `union` to

```ts
export interface UnionType<RTS extends [Any]> extends Type<TypeOf<RTS['_A']>> {
  readonly _tag: 'UnionType'
  readonly types: RTS
}

export function union<RTS extends [Any]>(types: RTS, name?: string): UnionType<RTS> {
  return {
    _A,
    _tag: 'UnionType',
    name: name || `(${types.map(type => type.name).join(' | ')})`,
    validate: (v, c) => {
      for (let i = 0; i < types.length; i++) {
        const validation = types[i].validate(v, c)
        if (isRight(validation)) {
          return validation
        }
      }
      return failure(v, c)
    },
    types
  }
}
```

it seems to handle infinite unions without requiring any overloading: the `extends [Any]` constraint forces TypeScript to consider `RTS` as a tuple (instead of an `Array`) and the `TypeOf<RTS['_A']>` bit extracts the union, because of the following declaration contained in fp-ts

```ts
declare global {
  interface Array<T> {
    _A: T
  }
}
```

/cc @pelotom
