### ISSUE TITLE
Missing types from fp-ts after upgrading to io-ts@1.10.0

### ISSUE THREAD

**Issue by noe132** [gcanti/io-ts#337]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
type definition failed after upgrade to 1.10.0 because I don't have `fp-ts` in my dependencies.
I see it referrence some type from `fp-ts`

```typescript
// lib/index.d.ts
import { Either } from 'fp-ts/lib/Either' // Cannot find module 'fp-ts/lib/Either'.
```

**What is the expected behavior?**

**Which versions of io-ts, and which browser and OS are affected by this issue? Did this work in previous versions of io-ts?**
`1.10.0`.
`1.8.6` I previously using was fine

**Comment by lostintime** [comment]
`fp-ts` is now a `peerDependency`, starting with `1.10`: https://github.com/gcanti/io-ts/commit/07dc8b1070060eaceeee61fc2003ab62fb67dc72#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R39

> UPDATE: npm versions 1 and 2 will automatically install peerDependencies if they are not explicitly depended upon higher in the dependency tree. For all following versions of npm (starting with npm@3), this will no longer be the case. You will receive a warning that the peerDependency is not installed instead.  (https://nodejs.org/en/blog/npm/peer-dependencies/)

**Comment by noe132** [comment]
Thanks for the reply! Looks manually add it to my dependencies would be fine. I think there could be some documentation in readme about this change in `1.10.0`

**Comment by gcanti** [comment]
@noe132 I've added an ["Installation"](https://github.com/gcanti/io-ts#installation) section to the README

**Comment by steida** [comment]
Thank you. It works now.
