### ISSUE TITLE
TypeOf operator is failing to compile after upgrading to TypeScript (3.1.1)

### ISSUE THREAD

**Issue by tetsuo** [gcanti/io-ts#211]
Hello @gcanti,

I've started getting some errors today after upgrading to TS 3.1.1. Following example is working fine with TS 3.0.3, but it doesn't compile with 3.1.1.

I have a custom `StringLength` type:

```typescript
import * as t from 'io-ts'

export class StringLength extends t.Type<string> {
  readonly _tag: 'StringLength' = 'StringLength'
  constructor(min: number, max: number) {
    super(
      `StringLength_${min}_${max}`,
      (m): m is string => typeof m === 'string' && (m.length >= min && m.length <= max),
      (m, c) => (this.is(m) ? t.success(m) : t.failure(m, c)),
      t.identity
    )
  }
}
```

And, I use it like this:

```typescript
export const StringLengthType = StringLength

export type StringLengthType = StringLength

export const StringLength_6_100 = new StringLengthType(6, 100)

export type StringLength_6_100 = t.TypeOf<typeof StringLengthType>
```

And, this is the error I'm getting, this doesn't happen with TS 3.0.3.

```
src/client/domain.ts:167:42 - error TS2344: Type 'typeof StringLength' does not satisfy the constraint 'Type<any, any, any>'.

167 export type StringLength_6_100 = t.TypeOf<typeof StringLengthType>
```

**Comment by sledorze** [comment]
Try 
```typescript
export type StringLength_6_100 = t.TypeOf<typeof StringLengthType>
```

**Comment by sledorze** [comment]
@tetsuo closing it because it has nothing to do with a regression.

**Comment by gcanti** [comment]
That's good, looks like a bug in TS 3.0.3. 

`StringLengthType` is not an instance of `t.Type` so this is illegal:

```ts
export type StringLength_6_100 = t.TypeOf<typeof StringLengthType>
```

**Comment by tetsuo** [comment]
Aha, thanks. That's a bug indeed. This shouldn't have worked in the first place.
